#!/usr/bin/env python

import os
import subprocess
import sys

sys.path.insert(0, '..')

from config import get_config
from logger import get_logger

log = get_logger(__name__)
cfg = get_config("LOCAL")

__location__ = os.path.realpath(
    os.path.join(os.getcwd(), os.path.dirname(__file__)))

subprocess.check_call([
  "docker",
  "build", ".",
  "-t", "%s:fusenet" % cfg['fusenet'].get("registry_url")
])
